In [12]:
# Using pandas, sqlalchemy and numpy in this analysis
import pandas as pd
from sqlalchemy import create_engine
import numpy as np

In [13]:
# Importing csv files to create dataframe
rest_file = "../data/dataset.csv"
data_df = pd.read_csv(rest_file)

# removing null values to avoid errors  
data_df.dropna(how ='all', inplace = True) 
data_df

,CAMIS,DBA,BORO,BUILDING,STREET,ZIPCODE,PHONE,CUISINE DESCRIPTION,INSPECTION DATE,ACTION,...,RECORD DATE,INSPECTION TYPE,Latitude,Longitude,Community Board,Council District,Census Tract,BIN,BBL,NTA
0,50045803,PUNJABI KABAB AND GYRO,Queens,10803,101ST AVE,11416,7187099919,Indian,2/2/2019,Violations were cited in the following area(s).,...,9/10/2020,Cycle Inspection / Re-inspection,40.687314,-73.835288,409,28,11000,4197917,4094100035,QN54
1,50060589,EL MARIACHI RESTAURNT,Queens,6712,ROOSEVELT AVE,11377,7183356744,Mexican,11/16/2018,Violations were cited in the following area(s).,...,9/10/2020,Cycle Inspection / Re-inspection,40.746152,-73.897899,402,26,26300,4000000,4012990027,QN63
2,41682808,JOSIE'S BAR,Manhattan,520,EAST 6 STREET,10009,2122289532,American,2/7/2018,Violations were cited in the following area(s).,...,9/10/2020,Cycle Inspection / Initial Inspection,40.725172,-73.983285,103,2,3200,1005052,1004010020,MN22
3,40483697,LUNT FONTANNE THEATER,Manhattan,205,WEST 46 STREET,10036,2123544624,American,5/3/2017,Violations were cited in the following area(s).,...,9/10/2020,Cycle Inspection / Initial Inspection,40.758891,-73.985796,105,3,12500,1024739,1010180020,MN17
4,50059948,ESTAMINET,Brooklyn,107A,7 AVENUE,11215,9174994191,Caf√©/Coffee/Tea,3/6/2019,Violations were cited in the following area(s).,...,9/10/2020,Cycle Inspection / Initial Inspection,40.673914,-73.975814,306,39,15700,3024679,3010650069,BK37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195393,50077488,MASAL CAFE,Brooklyn,1901,EMMONS AVENUE,11235,7188917090,Turkish,2/18/2020,Violations were cited in the following area(s).,...,9/10/2020,Cycle Inspection / Re-inspection,40.583558,-73.949432,315,48,60800,3326914,3087750041,BK17
195394,50069929,CHIKARASHI,Manhattan,1158,BROADWAY,10001,9172620623,Japanese,11/1/2019,Establishment re-opened by DOHMH,...,9/10/2020,Cycle Inspection / Reopening Inspection,40.744482,-73.988513,105,2,5800,1080699,1008290030,MN13
195395,40743578,EL RUMBERO BAR RESTAURANT,Queens,82-05,NORTHERN BOULEVARD,11372,7188033125,"Latin (Cuban, Dominican, Puerto Rican, South &...",11/25/2019,Establishment re-opened by DOHMH,...,9/10/2020,Cycle Inspection / Reopening Inspection,40.755577,-73.885200,403,25,32700,4034499,4014120047,QN28
195396,50086643,GOLDEN CITY RESTAURANT,Bronx,2324,ARTHUR AVENUE,10458,7185625885,Chinese,3/3/2020,Violations were cited in the following area(s).,...,9/10/2020,Cycle Inspection / Re-inspection,40.853927,-73.888952,206,15,39100,2012121,2030730005,BX06
195397,50051545,TSURUTONTAN UDON NOODLE BRASSERIE,Manhattan,21,EAST 16 STREET,10003,2129891000,Japanese,2/13/2020,Violations were cited in the following area(s).,...,9/10/2020,Cycle Inspection / Re-inspection,40.737096,-73.992090,105,2,5200,1078701,1008440017,MN13

In [22]:
data_df["CAMIS"].drop_duplicates(keep='last')

data_df

,CAMIS,DBA,BORO,BUILDING,STREET,ZIPCODE,PHONE,CUISINE DESCRIPTION,INSPECTION DATE,ACTION,...,RECORD DATE,INSPECTION TYPE,Latitude,Longitude,Community Board,Council District,Census Tract,BIN,BBL,NTA
0,50045803,PUNJABI KABAB AND GYRO,Queens,10803,101ST AVE,11416,7187099919,Indian,2/2/2019,Violations were cited in the following area(s).,...,9/10/2020,Cycle Inspection / Re-inspection,40.687314,-73.835288,409,28,11000,4197917,4094100035,QN54
1,50060589,EL MARIACHI RESTAURNT,Queens,6712,ROOSEVELT AVE,11377,7183356744,Mexican,11/16/2018,Violations were cited in the following area(s).,...,9/10/2020,Cycle Inspection / Re-inspection,40.746152,-73.897899,402,26,26300,4000000,4012990027,QN63
2,41682808,JOSIE'S BAR,Manhattan,520,EAST 6 STREET,10009,2122289532,American,2/7/2018,Violations were cited in the following area(s).,...,9/10/2020,Cycle Inspection / Initial Inspection,40.725172,-73.983285,103,2,3200,1005052,1004010020,MN22
3,40483697,LUNT FONTANNE THEATER,Manhattan,205,WEST 46 STREET,10036,2123544624,American,5/3/2017,Violations were cited in the following area(s).,...,9/10/2020,Cycle Inspection / Initial Inspection,40.758891,-73.985796,105,3,12500,1024739,1010180020,MN17
4,50059948,ESTAMINET,Brooklyn,107A,7 AVENUE,11215,9174994191,Caf√©/Coffee/Tea,3/6/2019,Violations were cited in the following area(s).,...,9/10/2020,Cycle Inspection / Initial Inspection,40.673914,-73.975814,306,39,15700,3024679,3010650069,BK37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195393,50077488,MASAL CAFE,Brooklyn,1901,EMMONS AVENUE,11235,7188917090,Turkish,2/18/2020,Violations were cited in the following area(s).,...,9/10/2020,Cycle Inspection / Re-inspection,40.583558,-73.949432,315,48,60800,3326914,3087750041,BK17
195394,50069929,CHIKARASHI,Manhattan,1158,BROADWAY,10001,9172620623,Japanese,11/1/2019,Establishment re-opened by DOHMH,...,9/10/2020,Cycle Inspection / Reopening Inspection,40.744482,-73.988513,105,2,5800,1080699,1008290030,MN13
195395,40743578,EL RUMBERO BAR RESTAURANT,Queens,82-05,NORTHERN BOULEVARD,11372,7188033125,"Latin (Cuban, Dominican, Puerto Rican, South &...",11/25/2019,Establishment re-opened by DOHMH,...,9/10/2020,Cycle Inspection / Reopening Inspection,40.755577,-73.885200,403,25,32700,4034499,4014120047,QN28
195396,50086643,GOLDEN CITY RESTAURANT,Bronx,2324,ARTHUR AVENUE,10458,7185625885,Chinese,3/3/2020,Violations were cited in the following area(s).,...,9/10/2020,Cycle Inspection / Re-inspection,40.853927,-73.888952,206,15,39100,2012121,2030730005,BX06
195397,50051545,TSURUTONTAN UDON NOODLE BRASSERIE,Manhattan,21,EAST 16 STREET,10003,2129891000,Japanese,2/13/2020,Violations were cited in the following area(s).,...,9/10/2020,Cycle Inspection / Re-inspection,40.737096,-73.992090,105,2,5200,1078701,1008440017,MN13

In [23]:
#data_df = pd.dataFrame(data_df)
# data_df.nunique(axis=1)
# data_df.head()

In [24]:
# using str.lower() to change letter case 

new= data_df.loc[:,['CAMIS','DBA','STREET']]
new['DBA']= new['DBA'].str.lower()
new['STREET']= new['STREET'].str.lower()
#dba.to_append()
#dba.join(nta)
data= pd.merge(data_df, new, on='CAMIS', how= 'outer')
data.head()

,CAMIS,DBA_x,BORO,BUILDING,STREET_x,ZIPCODE,PHONE,CUISINE DESCRIPTION,INSPECTION DATE,ACTION,...,Latitude,Longitude,Community Board,Council District,Census Tract,BIN,BBL,NTA,DBA_y,STREET_y
0,50045803,PUNJABI KABAB AND GYRO,Queens,10803,101ST AVE,11416,7187099919,Indian,2/2/2019,Violations were cited in the following area(s).,...,40.687314,-73.835288,409,28,11000,4197917,4094100035,QN54,punjabi kabab and gyro,101st ave
1,50045803,PUNJABI KABAB AND GYRO,Queens,10803,101ST AVE,11416,7187099919,Indian,2/2/2019,Violations were cited in the following area(s).,...,40.687314,-73.835288,409,28,11000,4197917,4094100035,QN54,punjabi kabab and gyro,101st ave
2,50045803,PUNJABI KABAB AND GYRO,Queens,10803,101ST AVE,11416,7187099919,Indian,2/2/2019,Violations were cited in the following area(s).,...,40.687314,-73.835288,409,28,11000,4197917,4094100035,QN54,punjabi kabab and gyro,101st ave
3,50045803,PUNJABI KABAB AND GYRO,Queens,10803,101ST AVE,11416,7187099919,Indian,2/2/2019,Violations were cited in the following area(s).,...,40.687314,-73.835288,409,28,11000,4197917,4094100035,QN54,punjabi kabab and gyro,101st ave
4,50045803,PUNJABI KABAB AND GYRO,Queens,10803,101ST AVE,11416,7187099919,Indian,2/2/2019,Violations were cited in the following area(s).,...,40.687314,-73.835288,409,28,11000,4197917,4094100035,QN54,punjabi kabab and gyro,101st ave

In [25]:
# Cleaning dataset by dropping useless columns and combine all same ids
newdata= data.drop(['DBA_x','STREET_x','GRADE DATE','RECORD DATE','Community Board','Council District', 'BIN','BBL','NTA'], axis=1)

newdata.head()

,CAMIS,BORO,BUILDING,ZIPCODE,PHONE,CUISINE DESCRIPTION,INSPECTION DATE,ACTION,VIOLATION CODE,VIOLATION DESCRIPTION,CRITICAL FLAG,SCORE,GRADE,INSPECTION TYPE,Latitude,Longitude,Census Tract,DBA_y,STREET_y
0,50045803,Queens,10803,11416,7187099919,Indian,2/2/2019,Violations were cited in the following area(s).,09C,Food contact surface not properly maintained.,N,11,A,Cycle Inspection / Re-inspection,40.687314,-73.835288,11000,punjabi kabab and gyro,101st ave
1,50045803,Queens,10803,11416,7187099919,Indian,2/2/2019,Violations were cited in the following area(s).,09C,Food contact surface not properly maintained.,N,11,A,Cycle Inspection / Re-inspection,40.687314,-73.835288,11000,punjabi kabab and gyro,101st ave
2,50045803,Queens,10803,11416,7187099919,Indian,2/2/2019,Violations were cited in the following area(s).,09C,Food contact surface not properly maintained.,N,11,A,Cycle Inspection / Re-inspection,40.687314,-73.835288,11000,punjabi kabab and gyro,101st ave
3,50045803,Queens,10803,11416,7187099919,Indian,2/2/2019,Violations were cited in the following area(s).,09C,Food contact surface not properly maintained.,N,11,A,Cycle Inspection / Re-inspection,40.687314,-73.835288,11000,punjabi kabab and gyro,101st ave
4,50045803,Queens,10803,11416,7187099919,Indian,2/2/2019,Violations were cited in the following area(s).,09C,Food contact surface not properly maintained.,N,11,A,Cycle Inspection / Re-inspection,40.687314,-73.835288,11000,punjabi kabab and gyro,101st ave

In [26]:
# Rename columns to lowercase for sql
newdata = newdata.rename(columns={"CAMIS": "record_id", "DBA_y" : "name", "BORO":"borough", "BUILDING":"building", "STREET_y":"street",
                                  "ZIPCODE":"zipcode","PHONE":"phone","CUISINE DESCRIPTION":"cuisine",
                                  "INSPECTION DATE":"inspection_date", "ACTION": "action", "VIOLATION CODE": "violation_code",
                                  "VIOLATION DESCRIPTION":"description",
                                  "CRITICAL FLAG":"flag", "SCORE":"score","GRADE":"grade","INSPECTION TYPE":"inspection_type",
                                 "Latitude":"lat","Longitude":"lng","Census Tract":"census_tract"})
newdata

,record_id,borough,building,zipcode,phone,cuisine,inspection_date,action,violation_code,description,flag,score,grade,inspection_type,lat,lng,census_tract,name,street
0,50045803,Queens,10803,11416,7187099919,Indian,2/2/2019,Violations were cited in the following area(s).,09C,Food contact surface not properly maintained.,N,11,A,Cycle Inspection / Re-inspection,40.687314,-73.835288,11000,punjabi kabab and gyro,101st ave
1,50045803,Queens,10803,11416,7187099919,Indian,2/2/2019,Violations were cited in the following area(s).,09C,Food contact surface not properly maintained.,N,11,A,Cycle Inspection / Re-inspection,40.687314,-73.835288,11000,punjabi kabab and gyro,101st ave
2,50045803,Queens,10803,11416,7187099919,Indian,2/2/2019,Violations were cited in the following area(s).,09C,Food contact surface not properly maintained.,N,11,A,Cycle Inspection / Re-inspection,40.687314,-73.835288,11000,punjabi kabab and gyro,101st ave
3,50045803,Queens,10803,11416,7187099919,Indian,2/2/2019,Violations were cited in the following area(s).,09C,Food contact surface not properly maintained.,N,11,A,Cycle Inspection / Re-inspection,40.687314,-73.835288,11000,punjabi kabab and gyro,101st ave
4,50045803,Queens,10803,11416,7187099919,Indian,2/2/2019,Violations were cited in the following area(s).,09C,Food contact surface not properly maintained.,N,11,A,Cycle Inspection / Re-inspection,40.687314,-73.835288,11000,punjabi kabab and gyro,101st ave
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1989745,50092613,Manhattan,500,10018,5162428036,American,12/19/2019,Violations were cited in the following area(s).,04A,Food Protection Certificate not held by superv...,Y,38,Z,Pre-permit (Operational) / Re-inspection,40.752985,-73.989186,10900,dr smood,7 avenue
1989746,50092613,Manhattan,500,10018,5162428036,American,12/19/2019,Violations were cited in the following area(s).,05E,Toilet facility not provided for employees or ...,Y,38,Z,Pre-permit (Operational) / Re-inspection,40.752985,-73.989186,10900,dr smood,7 avenue
1989747,50092613,Manhattan,500,10018,5162428036,American,12/19/2019,Violations were cited in the following area(s).,05E,Toilet facility not provided for employees or ...,Y,38,Z,Pre-permit (Operational) / Re-inspection,40.752985,-73.989186,10900,dr smood,7 avenue
1989748,50100492,Queens,2908,11354,7189614742,Korean,12/17/2019,Establishment re-opened by DOHMH,10F,Non-food contact surface improperly constructe...,N,2,Z,Pre-permit (Operational) / Reopening Inspection,40.771741,-73.826584,88901,bap jip,union st
1989749,50098865,Manhattan,513,10011,6468640575,Asian,11/29/2019,Establishment re-opened by DOHMH,10F,Non-food contact surface improperly constructe...,N,4,Z,Pre-permit (Operational) / Reopening Inspection,40.736915,-73.997171,7100,big bowl noodle,6 avenue

In [27]:
newdata.to_csv('dataset1.csv',index=False)

In [31]:
newdata2= newdata.head()
newdata2.to_csv('dataset2.csv',index=False)

In [ ]:
# # Connect to postgres by create engine 
# connection_string = "postgres:postgres@localhost:5432/restaurant_db"
# engine = create_engine(f'postgresql://{connection_string}')

In [ ]:
# # Confirm table names
# engine.table_names()

In [ ]:
## Load Dataframe into database

# newdata.to_sql(name='restaurant', con=engine, if_exists='append', index=True)